"""
Данные врождённых техник для гачи (см. gacha.py).

ТОЛЬКО данные: словарь TECHNIQUES. Логика гачи (роллы, экип, refund)
находится в gacha.py и импортирует TECHNIQUES отсюда.

Поля каждой техники:
    emoji      — эмодзи для отображения
    name       — имя техники (дублирует ключ, удобно для передачи объекта отдельно)
    rarity     — один из 5 уровней редкости (см. config.GACHA_RARITY_WEIGHTS)
    category   — "⚔️ Атака" | "🛡 Защита" | "🌀 Статус" (дебафф/бафф/исцеление)
    ce_cost    — стоимость в проклятой энергии
    dmg_min/dmg_max — диапазон урона (0/0 для чисто вспомогательных техник)
    effect     — None или словарь эффекта:
                   {"type": "bleed",    "turns": N, "dmg": N,  "chance": 0-1}
                   {"type": "stun",     "turns": N, "chance": 0-1}
                   {"type": "buff_dmg", "turns": N, "mult": >1, "chance": 0-1}
                   {"type": "buff_def", "turns": N, "mult": <1, "chance": 0-1}
                   {"type": "weaken",   "turns": N, "mult": <1, "chance": 0-1}
                   {"type": "heal",     "turns": 0, "amount": N, "chance": 0-1}
    has_domain — True только у мастер-техники семьи.

Всего 120 техник, из них has_domain=True — только у 19 (мастера семей).
"""

TECHNIQUES = {
    "Вихревой клинок I": {
        "emoji": '🌪️', "name": 'Вихревой клинок I',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 10,
        "dmg_min": 6, "dmg_max": 11,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.3},
        "desc": 'Вихревой клинок I — проклятая техника ближнего боя, (30% стан на 1 ход).',
        "has_domain": False,
    },
    "Волчий укус I": {
        "emoji": '🐺', "name": 'Волчий укус I',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 7,
        "dmg_min": 6, "dmg_max": 8,
        "effect": None,
        "desc": 'Волчий укус I — проклятая техника ближнего боя, чистый физический урон без побочных эффектов.',
        "has_domain": False,
    },
    "Змеиный выпад I": {
        "emoji": '🐍', "name": 'Змеиный выпад I',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 8,
        "dmg_min": 4, "dmg_max": 9,
        "effect": None,
        "desc": 'Змеиный выпад I — проклятая техника ближнего боя, чистый физический урон без побочных эффектов.',
        "has_domain": False,
    },
    "Игольчатый залп I": {
        "emoji": '📌', "name": 'Игольчатый залп I',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 8,
        "dmg_min": 7, "dmg_max": 9,
        "effect": {'type': 'bleed', 'turns': 2, 'dmg': 3, 'chance': 0.45},
        "desc": 'Игольчатый залп I — проклятая техника ближнего боя, (45% кровотечение 2 хода).',
        "has_domain": False,
    },
    "Клинок пустоты I": {
        "emoji": '🗡️', "name": 'Клинок пустоты I',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 10,
        "dmg_min": 4, "dmg_max": 11,
        "effect": {'type': 'bleed', 'turns': 2, 'dmg': 3, 'chance': 0.45},
        "desc": 'Клинок пустоты I — проклятая техника ближнего боя, (45% кровотечение 2 хода).',
        "has_domain": False,
    },
    "Молот проклятия I": {
        "emoji": '🔨', "name": 'Молот проклятия I',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 7,
        "dmg_min": 7, "dmg_max": 8,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.3},
        "desc": 'Молот проклятия I — проклятая техника ближнего боя, (30% стан на 1 ход).',
        "has_domain": False,
    },
    "Осколочный удар I": {
        "emoji": '💎', "name": 'Осколочный удар I',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 9,
        "dmg_min": 5, "dmg_max": 10,
        "effect": {'type': 'bleed', 'turns': 2, 'dmg': 3, 'chance': 0.45},
        "desc": 'Осколочный удар I — проклятая техника ближнего боя, (45% кровотечение 2 хода).',
        "has_domain": False,
    },
    "Проклятая заноза I": {
        "emoji": '🩹', "name": 'Проклятая заноза I',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 10,
        "dmg_min": 5, "dmg_max": 11,
        "effect": None,
        "desc": 'Проклятая заноза I — проклятая техника ближнего боя, чистый физический урон без побочных эффектов.',
        "has_domain": False,
    },
    "Проклятый росчерк I": {
        "emoji": '🌀', "name": 'Проклятый росчерк I',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 6,
        "dmg_min": 4, "dmg_max": 7,
        "effect": None,
        "desc": 'Проклятый росчерк I — проклятая техника ближнего боя, чистый физический урон без побочных эффектов.',
        "has_domain": False,
    },
    "Пуля построения": {
        "emoji": '🔫', "name": 'Пуля построения',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 9,
        "dmg_min": 5, "dmg_max": 8,
        "effect": None,
        "desc": 'Маи Зенин сплетает снаряд прямо из ПЭ ствола, экономя обычные патроны.',
        "has_domain": False,
    },
    "Разряд контура I": {
        "emoji": '⚡', "name": 'Разряд контура I',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 9,
        "dmg_min": 7, "dmg_max": 10,
        "effect": None,
        "desc": 'Разряд контура I — проклятая техника ближнего боя, чистый физический урон без побочных эффектов.',
        "has_domain": False,
    },
    "Раскол контура I": {
        "emoji": '💢', "name": 'Раскол контура I',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 9,
        "dmg_min": 4, "dmg_max": 10,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.3},
        "desc": 'Раскол контура I — проклятая техника ближнего боя, (30% стан на 1 ход).',
        "has_domain": False,
    },
    "Серп теней I": {
        "emoji": '🌙', "name": 'Серп теней I',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 6,
        "dmg_min": 6, "dmg_max": 7,
        "effect": {'type': 'bleed', 'turns': 2, 'dmg': 3, 'chance': 0.45},
        "desc": 'Серп теней I — проклятая техника ближнего боя, (45% кровотечение 2 хода).',
        "has_domain": False,
    },
    "Терновый выпад I": {
        "emoji": '🌵', "name": 'Терновый выпад I',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 8,
        "dmg_min": 6, "dmg_max": 9,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.3},
        "desc": 'Терновый выпад I — проклятая техника ближнего боя, (30% стан на 1 ход).',
        "has_domain": False,
    },
    "Хлыст ПЭ I": {
        "emoji": '〰️', "name": 'Хлыст ПЭ I',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 6,
        "dmg_min": 5, "dmg_max": 7,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.3},
        "desc": 'Хлыст ПЭ I — проклятая техника ближнего боя, (30% стан на 1 ход).',
        "has_domain": False,
    },
    "Чёрный клык I": {
        "emoji": '🖤', "name": 'Чёрный клык I',
        "rarity": 'Обычная', "category": '⚔️ Атака',
        "ce_cost": 7,
        "dmg_min": 5, "dmg_max": 8,
        "effect": {'type': 'bleed', 'turns': 2, 'dmg': 3, 'chance': 0.45},
        "desc": 'Чёрный клык I — проклятая техника ближнего боя, (45% кровотечение 2 хода).',
        "has_domain": False,
    },
    "Броня контура I": {
        "emoji": '🎽', "name": 'Броня контура I',
        "rarity": 'Обычная', "category": '🛡 Защита',
        "ce_cost": 9,
        "dmg_min": 4, "dmg_max": 6,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.79, 'chance': 1.0},
        "desc": 'Броня контура I — защитная проклятая техника (-21% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Заслон проклятия I": {
        "emoji": '🚧', "name": 'Заслон проклятия I',
        "rarity": 'Обычная', "category": '🛡 Защита',
        "ce_cost": 7,
        "dmg_min": 4, "dmg_max": 6,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.77, 'chance': 1.0},
        "desc": 'Заслон проклятия I — защитная проклятая техника (-23% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Кокон защиты I": {
        "emoji": '🕸️', "name": 'Кокон защиты I',
        "rarity": 'Обычная', "category": '🛡 Защита',
        "ce_cost": 7,
        "dmg_min": 4, "dmg_max": 6,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.81, 'chance': 1.0},
        "desc": 'Кокон защиты I — защитная проклятая техника (-19% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Купол стойкости I": {
        "emoji": '⛺', "name": 'Купол стойкости I',
        "rarity": 'Обычная', "category": '🛡 Защита',
        "ce_cost": 10,
        "dmg_min": 4, "dmg_max": 6,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.78, 'chance': 1.0},
        "desc": 'Купол стойкости I — защитная проклятая техника (-22% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Отражающий покров I": {
        "emoji": '🪞', "name": 'Отражающий покров I',
        "rarity": 'Обычная', "category": '🛡 Защита',
        "ce_cost": 8,
        "dmg_min": 4, "dmg_max": 6,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.8, 'chance': 1.0},
        "desc": 'Отражающий покров I — защитная проклятая техника (-20% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Панцирь контура I": {
        "emoji": '🐚', "name": 'Панцирь контура I',
        "rarity": 'Обычная', "category": '🛡 Защита',
        "ce_cost": 8,
        "dmg_min": 4, "dmg_max": 6,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.84, 'chance': 1.0},
        "desc": 'Панцирь контура I — защитная проклятая техника (-16% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Проклятый барьер I": {
        "emoji": '🧱', "name": 'Проклятый барьер I',
        "rarity": 'Обычная', "category": '🛡 Защита',
        "ce_cost": 7,
        "dmg_min": 4, "dmg_max": 6,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.85, 'chance': 1.0},
        "desc": 'Проклятый барьер I — защитная проклятая техника (-15% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Стена ПЭ I": {
        "emoji": '🧱', "name": 'Стена ПЭ I',
        "rarity": 'Обычная', "category": '🛡 Защита',
        "ce_cost": 10,
        "dmg_min": 4, "dmg_max": 6,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.82, 'chance': 1.0},
        "desc": 'Стена ПЭ I — защитная проклятая техника (-18% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Твёрдая корка ПЭ I": {
        "emoji": '🪨', "name": 'Твёрдая корка ПЭ I',
        "rarity": 'Обычная', "category": '🛡 Защита',
        "ce_cost": 8,
        "dmg_min": 4, "dmg_max": 6,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.76, 'chance': 1.0},
        "desc": 'Твёрдая корка ПЭ I — защитная проклятая техника (-24% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Щит из теней I": {
        "emoji": '🛡️', "name": 'Щит из теней I',
        "rarity": 'Обычная', "category": '🛡 Защита',
        "ce_cost": 9,
        "dmg_min": 4, "dmg_max": 6,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.83, 'chance': 1.0},
        "desc": 'Щит из теней I — защитная проклятая техника (-17% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Вихрь дезориентации I": {
        "emoji": '🌀', "name": 'Вихрь дезориентации I',
        "rarity": 'Обычная', "category": '🌀 Статус',
        "ce_cost": 11,
        "dmg_min": 2, "dmg_max": 4,
        "effect": {'type': 'weaken', 'turns': 2, 'mult': 0.79, 'chance': 0.5},
        "desc": 'Вихрь дезориентации I — техника подавления (50% -20% урона цели на 2 хода).',
        "has_domain": False,
    },
    "Всплеск адреналина ПЭ I": {
        "emoji": '💉', "name": 'Всплеск адреналина ПЭ I',
        "rarity": 'Обычная', "category": '🌀 Статус',
        "ce_cost": 9,
        "dmg_min": 0, "dmg_max": 0,
        "effect": {'type': 'heal', 'turns': 0, 'amount': 12, 'chance': 1.0},
        "desc": 'Всплеск адреналина ПЭ I — исцеляющая техника (мгновенно 12 HP).',
        "has_domain": False,
    },
    "Клеймо слабости I": {
        "emoji": '🏷️', "name": 'Клеймо слабости I',
        "rarity": 'Обычная', "category": '🌀 Статус',
        "ce_cost": 8,
        "dmg_min": 2, "dmg_max": 4,
        "effect": {'type': 'weaken', 'turns': 2, 'mult': 0.82, 'chance': 0.5},
        "desc": 'Клеймо слабости I — техника подавления (50% -17% урона цели на 2 хода).',
        "has_domain": False,
    },
    "Печать молчания I": {
        "emoji": '🤐', "name": 'Печать молчания I',
        "rarity": 'Обычная', "category": '🌀 Статус',
        "ce_cost": 9,
        "dmg_min": 3, "dmg_max": 5,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.4},
        "desc": 'Печать молчания I — техника дезориентации (40% стан на 1 ход).',
        "has_domain": False,
    },
    "Прилив стойкости I": {
        "emoji": '💪', "name": 'Прилив стойкости I',
        "rarity": 'Обычная', "category": '🌀 Статус',
        "ce_cost": 10,
        "dmg_min": 3, "dmg_max": 5,
        "effect": {'type': 'buff_dmg', 'turns': 2, 'mult': 1.25, 'chance': 1.0},
        "desc": 'Прилив стойкости I — техника поддержки (+25% урона на 2 хода).',
        "has_domain": False,
    },
    "Проклятая метка I": {
        "emoji": '🔖', "name": 'Проклятая метка I',
        "rarity": 'Обычная', "category": '🌀 Статус',
        "ce_cost": 8,
        "dmg_min": 3, "dmg_max": 5,
        "effect": {'type': 'buff_dmg', 'turns': 2, 'mult': 1.2, 'chance': 1.0},
        "desc": 'Проклятая метка I — техника поддержки (+19% урона на 2 хода).',
        "has_domain": False,
    },
    "Проклятая эйфория I": {
        "emoji": '🌈', "name": 'Проклятая эйфория I',
        "rarity": 'Обычная', "category": '🌀 Статус',
        "ce_cost": 10,
        "dmg_min": 3, "dmg_max": 5,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.4},
        "desc": 'Проклятая эйфория I — техника дезориентации (40% стан на 1 ход).',
        "has_domain": False,
    },
    "Проклятое благословение I": {
        "emoji": '✨', "name": 'Проклятое благословение I',
        "rarity": 'Обычная', "category": '🌀 Статус',
        "ce_cost": 11,
        "dmg_min": 3, "dmg_max": 5,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.4},
        "desc": 'Проклятое благословение I — техника дезориентации (40% стан на 1 ход).',
        "has_domain": False,
    },
    "Проклятое оцепенение I": {
        "emoji": '🥶', "name": 'Проклятое оцепенение I',
        "rarity": 'Обычная', "category": '🌀 Статус',
        "ce_cost": 8,
        "dmg_min": 0, "dmg_max": 0,
        "effect": {'type': 'heal', 'turns': 0, 'amount': 12, 'chance': 1.0},
        "desc": 'Проклятое оцепенение I — исцеляющая техника (мгновенно 12 HP).',
        "has_domain": False,
    },
    "Пульс восстановления I": {
        "emoji": '💗', "name": 'Пульс восстановления I',
        "rarity": 'Обычная', "category": '🌀 Статус',
        "ce_cost": 11,
        "dmg_min": 3, "dmg_max": 5,
        "effect": {'type': 'buff_dmg', 'turns': 2, 'mult': 1.25, 'chance': 1.0},
        "desc": 'Пульс восстановления I — техника поддержки (+25% урона на 2 хода).',
        "has_domain": False,
    },
    "Разряд ярости I": {
        "emoji": '😤', "name": 'Разряд ярости I',
        "rarity": 'Обычная', "category": '🌀 Статус',
        "ce_cost": 10,
        "dmg_min": 0, "dmg_max": 0,
        "effect": {'type': 'heal', 'turns': 0, 'amount': 13, 'chance': 1.0},
        "desc": 'Разряд ярости I — исцеляющая техника (мгновенно 13 HP).',
        "has_domain": False,
    },
    "Разрядка контура I": {
        "emoji": '🔋', "name": 'Разрядка контура I',
        "rarity": 'Обычная', "category": '🌀 Статус',
        "ce_cost": 12,
        "dmg_min": 3, "dmg_max": 4,
        "effect": {'type': 'weaken', 'turns': 2, 'mult': 0.78, 'chance': 0.5},
        "desc": 'Разрядка контура I — техника подавления (50% -21% урона цели на 2 хода).',
        "has_domain": False,
    },
    "Ток обновления I": {
        "emoji": '💫', "name": 'Ток обновления I',
        "rarity": 'Обычная', "category": '🌀 Статус',
        "ce_cost": 12,
        "dmg_min": 4, "dmg_max": 6,
        "effect": {'type': 'buff_dmg', 'turns': 2, 'mult': 1.25, 'chance': 1.0},
        "desc": 'Ток обновления I — техника поддержки (+25% урона на 2 хода).',
        "has_domain": False,
    },
    "Шёпот усталости I": {
        "emoji": '😴', "name": 'Шёпот усталости I',
        "rarity": 'Обычная', "category": '🌀 Статус',
        "ce_cost": 9,
        "dmg_min": 2, "dmg_max": 4,
        "effect": {'type': 'weaken', 'turns': 2, 'mult': 0.81, 'chance': 0.5},
        "desc": 'Шёпот усталости I — техника подавления (50% -18% урона цели на 2 хода).',
        "has_domain": False,
    },
    "Гарпун контура II": {
        "emoji": '🎣', "name": 'Гарпун контура II',
        "rarity": 'Редкая', "category": '⚔️ Атака',
        "ce_cost": 15,
        "dmg_min": 9, "dmg_max": 13,
        "effect": {'type': 'bleed', 'turns': 2, 'dmg': 5, 'chance': 0.6},
        "desc": 'Гарпун контура II — проклятая техника ближнего боя, (60% кровотечение 2 хода).',
        "has_domain": False,
    },
    "Зеркальный удар": {
        "emoji": '🪞', "name": 'Зеркальный удар',
        "rarity": 'Редкая', "category": '⚔️ Атака',
        "ce_cost": 17,
        "dmg_min": 9, "dmg_max": 13,
        "effect": None,
        "desc": 'Отражённая проклятая энергия бьёт с неожиданного угла через проклятое зеркало.',
        "has_domain": False,
    },
    "Клеймо боли II": {
        "emoji": '🔥', "name": 'Клеймо боли II',
        "rarity": 'Редкая', "category": '⚔️ Атака',
        "ce_cost": 14,
        "dmg_min": 9, "dmg_max": 12,
        "effect": {'type': 'bleed', 'turns': 2, 'dmg': 5, 'chance': 0.6},
        "desc": 'Клеймо боли II — проклятая техника ближнего боя, (60% кровотечение 2 хода).',
        "has_domain": False,
    },
    "Кровавый шип II": {
        "emoji": '🌹', "name": 'Кровавый шип II',
        "rarity": 'Редкая', "category": '⚔️ Атака',
        "ce_cost": 14,
        "dmg_min": 8, "dmg_max": 12,
        "effect": None,
        "desc": 'Кровавый шип II — проклятая техника ближнего боя, чистый физический урон без побочных эффектов.',
        "has_domain": False,
    },
    "Лунный разрез": {
        "emoji": '🌙', "name": 'Лунный разрез',
        "rarity": 'Редкая', "category": '⚔️ Атака',
        "ce_cost": 17,
        "dmg_min": 10, "dmg_max": 14,
        "effect": None,
        "desc": 'Клинок, заряженный лунным светом проклятой энергии, режет по дуге.',
        "has_domain": False,
    },
    "Мгновенный клинок": {
        "emoji": '⚡', "name": 'Мгновенный клинок',
        "rarity": 'Редкая', "category": '⚔️ Атака',
        "ce_cost": 16,
        "dmg_min": 10, "dmg_max": 14,
        "effect": None,
        "desc": 'Наоя телепортируется вплотную к цели и рубит прежде, чем противник успевает моргнуть.',
        "has_domain": False,
    },
    "Пробивной выстрел": {
        "emoji": '🎯', "name": 'Пробивной выстрел',
        "rarity": 'Редкая', "category": '⚔️ Атака',
        "ce_cost": 16,
        "dmg_min": 9, "dmg_max": 13,
        "effect": None,
        "desc": 'Усиленный снаряд ПЭ, пробивающий несколько слоёв проклятой защиты подряд.',
        "has_domain": False,
    },
    "Проклятая картечь II": {
        "emoji": '💥', "name": 'Проклятая картечь II',
        "rarity": 'Редкая', "category": '⚔️ Атака',
        "ce_cost": 16,
        "dmg_min": 10, "dmg_max": 14,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.45},
        "desc": 'Проклятая картечь II — проклятая техника ближнего боя, (45% стан на 1 ход).',
        "has_domain": False,
    },
    "Разрывной толчок II": {
        "emoji": '👐', "name": 'Разрывной толчок II',
        "rarity": 'Редкая', "category": '⚔️ Атака',
        "ce_cost": 17,
        "dmg_min": 8, "dmg_max": 15,
        "effect": None,
        "desc": 'Разрывной толчок II — проклятая техника ближнего боя, чистый физический урон без побочных эффектов.',
        "has_domain": False,
    },
    "Стрела крови": {
        "emoji": '🩸', "name": 'Стрела крови',
        "rarity": 'Редкая', "category": '⚔️ Атака',
        "ce_cost": 17,
        "dmg_min": 10, "dmg_max": 14,
        "effect": {'type': 'bleed', 'turns': 2, 'dmg': 6, 'chance': 0.5},
        "desc": 'Чосо формирует стрелу из собственной проклятой крови (50% кровотечение 2 хода).',
        "has_domain": False,
    },
    "Удар проклятого трупа": {
        "emoji": '🪆', "name": 'Удар проклятого трупа',
        "rarity": 'Редкая', "category": '⚔️ Атака',
        "ce_cost": 16,
        "dmg_min": 9, "dmg_max": 13,
        "effect": None,
        "desc": 'Уи Уи управляет марионеткой на расстоянии, нанося удар оттуда, где его не ждут.',
        "has_domain": False,
    },
    "Удар семь-три": {
        "emoji": '✊', "name": 'Удар семь-три',
        "rarity": 'Редкая', "category": '⚔️ Атака',
        "ce_cost": 16,
        "dmg_min": 9, "dmg_max": 13,
        "effect": None,
        "desc": 'Нанами бьёт с точным распределением силы 70% на 30% — фирменный коэффициент.',
        "has_domain": False,
    },
    "Каменная кожа II": {
        "emoji": '🗿', "name": 'Каменная кожа II',
        "rarity": 'Редкая', "category": '🛡 Защита',
        "ce_cost": 16,
        "dmg_min": 5, "dmg_max": 8,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.73, 'chance': 1.0},
        "desc": 'Каменная кожа II — защитная техника (-27% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Плетёный доспех II": {
        "emoji": '🧵', "name": 'Плетёный доспех II',
        "rarity": 'Редкая', "category": '🛡 Защита',
        "ce_cost": 15,
        "dmg_min": 5, "dmg_max": 7,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.75, 'chance': 1.0},
        "desc": 'Плетёный доспех II — защитная техника (-25% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Проклятая чешуя II": {
        "emoji": '🐉', "name": 'Проклятая чешуя II',
        "rarity": 'Редкая', "category": '🛡 Защита',
        "ce_cost": 17,
        "dmg_min": 5, "dmg_max": 8,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.71, 'chance': 1.0},
        "desc": 'Проклятая чешуя II — защитная техника (-28% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Слой рассеивания II": {
        "emoji": '🌫️', "name": 'Слой рассеивания II',
        "rarity": 'Редкая', "category": '🛡 Защита',
        "ce_cost": 18,
        "dmg_min": 6, "dmg_max": 9,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.69, 'chance': 1.0},
        "desc": 'Слой рассеивания II — защитная техника (-31% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Стальной панцирь": {
        "emoji": '🛡️', "name": 'Стальной панцирь',
        "rarity": 'Редкая', "category": '🛡 Защита',
        "ce_cost": 17,
        "dmg_min": 10, "dmg_max": 14,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.8, 'chance': 1.0},
        "desc": 'ПЭ застывает коркой проклятой стали на теле пользователя (-20% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Божественные псы": {
        "emoji": '🐕', "name": 'Божественные псы',
        "rarity": 'Редкая', "category": '🌀 Статус',
        "ce_cost": 18,
        "dmg_min": 8, "dmg_max": 12,
        "effect": {'type': 'bleed', 'turns': 2, 'dmg': 5, 'chance': 0.55},
        "desc": 'Призванная пара шикигами атакует с фронта и тыла (55% кровотечение 2 хода).',
        "has_domain": False,
    },
    "Искажение равновесия II": {
        "emoji": '⚖️', "name": 'Искажение равновесия II',
        "rarity": 'Редкая', "category": '🌀 Статус',
        "ce_cost": 17,
        "dmg_min": 4, "dmg_max": 5,
        "effect": {'type': 'weaken', 'turns': 2, 'mult': 0.73, 'chance': 0.5},
        "desc": 'Искажение равновесия II — техника подавления (50% -27% урона цели на 2 хода).',
        "has_domain": False,
    },
    "Плач раненых душ": {
        "emoji": '😢', "name": 'Плач раненых душ',
        "rarity": 'Редкая', "category": '🌀 Статус',
        "ce_cost": 16,
        "dmg_min": 0, "dmg_max": 0,
        "effect": {'type': 'heal', 'turns': 0, 'amount': 12, 'chance': 1.0},
        "desc": 'Скорбная песнь частично восстанавливает силы союзника (мгновенно 12 HP).',
        "has_domain": False,
    },
    "Проклятая жажда II": {
        "emoji": '🩸', "name": 'Проклятая жажда II',
        "rarity": 'Редкая', "category": '🌀 Статус',
        "ce_cost": 16,
        "dmg_min": 5, "dmg_max": 8,
        "effect": {'type': 'buff_dmg', 'turns': 2, 'mult': 1.25, 'chance': 1.0},
        "desc": 'Проклятая жажда II — техника поддержки (+25% урона на 2 хода).',
        "has_domain": False,
    },
    "Слово: Стой": {
        "emoji": '🗣️', "name": 'Слово: Стой',
        "rarity": 'Редкая', "category": '🌀 Статус',
        "ce_cost": 15,
        "dmg_min": 5, "dmg_max": 8,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.6},
        "desc": 'Проклятая речь Инумаки останавливает противника (60% стан на 1 ход).',
        "has_domain": False,
    },
    "Смена позиций": {
        "emoji": '🔄', "name": 'Смена позиций',
        "rarity": 'Редкая', "category": '🌀 Статус',
        "ce_cost": 17,
        "dmg_min": 7, "dmg_max": 11,
        "effect": {'type': 'buff_dmg', 'turns': 1, 'mult': 1.25, 'chance': 1.0},
        "desc": 'Буги-вуги Тодо меняет местами цели (+25% урона на 1 ход).',
        "has_domain": False,
    },
    "Тёплый след ПЭ II": {
        "emoji": '🕯️', "name": 'Тёплый след ПЭ II',
        "rarity": 'Редкая', "category": '🌀 Статус',
        "ce_cost": 18,
        "dmg_min": 0, "dmg_max": 0,
        "effect": {'type': 'heal', 'turns': 0, 'amount': 17, 'chance': 1.0},
        "desc": 'Тёплый след ПЭ II — исцеляющая техника (мгновенно 17 HP).',
        "has_domain": False,
    },
    "Шёпот тьмы": {
        "emoji": '🕳️', "name": 'Шёпот тьмы',
        "rarity": 'Редкая', "category": '🌀 Статус',
        "ce_cost": 16,
        "dmg_min": 6, "dmg_max": 9,
        "effect": {'type': 'weaken', 'turns': 2, 'mult': 0.85, 'chance': 0.55},
        "desc": 'Проклятый шёпот подтачивает решимость цели (55% -15% урона цели на 2 хода).',
        "has_domain": False,
    },
    "Буги-вуги Блиц": {
        "emoji": '👊', "name": 'Буги-вуги Блиц',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 27,
        "dmg_min": 18, "dmg_max": 24,
        "effect": None,
        "desc": 'Тодо телепортирует себя за спину проклятия через хлопок пальцами.',
        "has_domain": False,
    },
    "Громовой разряд": {
        "emoji": '⚡', "name": 'Громовой разряд',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 28,
        "dmg_min": 18, "dmg_max": 24,
        "effect": None,
        "desc": 'Проклятая молния бьёт по кратчайшему пути к цели, игнорируя уклонение.',
        "has_domain": False,
    },
    "Исчезающий росчерк": {
        "emoji": '🌀', "name": 'Исчезающий росчерк',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 27,
        "dmg_min": 18, "dmg_max": 24,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.35},
        "desc": 'Серия молниеносных телепортаций вокруг цели (35% стан на 1 ход).',
        "has_domain": False,
    },
    "Коготь тьмы": {
        "emoji": '🐾', "name": 'Коготь тьмы',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 27,
        "dmg_min": 18, "dmg_max": 24,
        "effect": {'type': 'bleed', 'turns': 2, 'dmg': 8, 'chance': 0.6},
        "desc": 'Проклятый зверь полосует цель невидимыми когтями (60% кровотечение 2 хода).',
        "has_domain": False,
    },
    "Красный": {
        "emoji": '🔴', "name": 'Красный',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 28,
        "dmg_min": 20, "dmg_max": 26,
        "effect": None,
        "desc": 'Отталкивающий разряд Бесконечности — взрывной удар отражённой ПЭ.',
        "has_domain": False,
    },
    "Ледяной укол": {
        "emoji": '❄️', "name": 'Ледяной укол',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 27,
        "dmg_min": 17, "dmg_max": 23,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.45},
        "desc": 'Игла из мгновенно замёрзшей ПЭ пронзает и сковывает сустав (45% стан на 1 ход).',
        "has_domain": False,
    },
    "Нуэ": {
        "emoji": '🦉', "name": 'Нуэ',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 27,
        "dmg_min": 17, "dmg_max": 23,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.4},
        "desc": 'Грозовой шикигами бьёт с воздуха раскатом молнии (40% стан на 1 ход).',
        "has_domain": False,
    },
    "Пепельный укол": {
        "emoji": '🔥', "name": 'Пепельный укол',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 27,
        "dmg_min": 17, "dmg_max": 23,
        "effect": {'type': 'bleed', 'turns': 2, 'dmg': 7, 'chance': 0.55},
        "desc": 'Проклятая техника рассеивания в пепел (55% кровотечение 2 хода).',
        "has_domain": False,
    },
    "Полумрак клинка": {
        "emoji": '🌘', "name": 'Полумрак клинка',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 28,
        "dmg_min": 18, "dmg_max": 24,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.4},
        "desc": 'Затемнение зрения цели в момент удара (40% стан на 1 ход).',
        "has_domain": False,
    },
    "Пронзающий манипулятор крови": {
        "emoji": '🎯', "name": 'Пронзающий манипулятор крови',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 28,
        "dmg_min": 18, "dmg_max": 24,
        "effect": None,
        "desc": 'Управляемая на расстоянии кровь меняет траекторию в полёте, обходя любой блок.',
        "has_domain": False,
    },
    "Разряд звёздной ярости": {
        "emoji": '⭐', "name": 'Разряд звёздной ярости',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 27,
        "dmg_min": 18, "dmg_max": 24,
        "effect": {'type': 'buff_dmg', 'turns': 2, 'mult': 1.35, 'chance': 1.0},
        "desc": 'Цукумо разгоняет себя до нечеловеческой скорости удара (+35% урона на 2 хода).',
        "has_domain": False,
    },
    "Расщепление": {
        "emoji": '🩸', "name": 'Расщепление',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 30,
        "dmg_min": 20, "dmg_max": 26,
        "effect": {'type': 'bleed', 'turns': 3, 'dmg': 8, 'chance': 0.65},
        "desc": 'Невидимая режущая сеть Сукуны (65% кровотечение 3 хода).',
        "has_domain": False,
    },
    "Роящиеся искры": {
        "emoji": '✨', "name": 'Роящиеся искры',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 27,
        "dmg_min": 17, "dmg_max": 23,
        "effect": {'type': 'bleed', 'turns': 2, 'dmg': 7, 'chance': 0.5},
        "desc": 'Рой огненных насекомых-проклятий облепляет цель (50% кровотечение 2 хода).',
        "has_domain": False,
    },
    "Сверхурочный коэффициент": {
        "emoji": '⏱️', "name": 'Сверхурочный коэффициент',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 27,
        "dmg_min": 19, "dmg_max": 25,
        "effect": {'type': 'buff_dmg', 'turns': 2, 'mult': 1.3, 'chance': 1.0},
        "desc": 'Нанами включает сверхурочные — расчётливый удар мачете (+30% урона на 2 хода).',
        "has_domain": False,
    },
    "Синий": {
        "emoji": '🔵', "name": 'Синий',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 28,
        "dmg_min": 18, "dmg_max": 24,
        "effect": {'type': 'buff_dmg', 'turns': 2, 'mult': 1.3, 'chance': 1.0},
        "desc": 'Притягивающий разряд Бесконечности (+30% физ. урона союзнику на 2 хода).',
        "has_domain": False,
    },
    "Удар на кону": {
        "emoji": '🎲', "name": 'Удар на кону',
        "rarity": 'Эпическая', "category": '⚔️ Атака',
        "ce_cost": 26,
        "dmg_min": 16, "dmg_max": 24,
        "effect": None,
        "desc": 'Проклятая энергия Хакари, помноженная на ставку в его личной игре.',
        "has_domain": False,
    },
    "Реактивная мутация": {
        "emoji": '🧬', "name": 'Реактивная мутация',
        "rarity": 'Эпическая', "category": '🛡 Защита',
        "ce_cost": 26,
        "dmg_min": 15, "dmg_max": 20,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.75, 'chance': 1.0},
        "desc": 'Ёрозу подстраивает тело под тип урона (-25% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Касание душ": {
        "emoji": '👋', "name": 'Касание душ',
        "rarity": 'Эпическая', "category": '🌀 Статус',
        "ce_cost": 26,
        "dmg_min": 14, "dmg_max": 20,
        "effect": {'type': 'buff_dmg', 'turns': 2, 'mult': 1.4, 'chance': 1.0},
        "desc": 'Прикосновение усиливает инстинктивную агрессию (+40% физ. урона на 2 хода).',
        "has_domain": False,
    },
    "Кровавая присяга": {
        "emoji": '🩸', "name": 'Кровавая присяга',
        "rarity": 'Эпическая', "category": '🌀 Статус',
        "ce_cost": 26,
        "dmg_min": 15, "dmg_max": 21,
        "effect": {'type': 'buff_dmg', 'turns': 2, 'mult': 1.4, 'chance': 1.0},
        "desc": 'Пользователь скрепляет удар собственной кровью (+40% урона на 2 хода).',
        "has_domain": False,
    },
    "Отражённый рок": {
        "emoji": '🪞', "name": 'Отражённый рок',
        "rarity": 'Эпическая', "category": '🌀 Статус',
        "ce_cost": 27,
        "dmg_min": 16, "dmg_max": 22,
        "effect": {'type': 'weaken', 'turns': 2, 'mult': 0.8, 'chance': 0.6},
        "desc": 'Часть урона проклятия отражается обратно (60% -20% урона цели на 2 хода).',
        "has_domain": False,
    },
    "Взрывное пламя": {
        "emoji": '💥', "name": 'Взрывное пламя',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 35,
        "dmg_min": 28, "dmg_max": 36,
        "effect": None,
        "desc": 'Направленный взрыв вулканической ПЭ — сносит защиту проклятия одним ударом.',
        "has_domain": False,
    },
    "Волна морского божества": {
        "emoji": '🌊', "name": 'Волна морского божества',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 33,
        "dmg_min": 24, "dmg_max": 32,
        "effect": {'type': 'bleed', 'turns': 2, 'dmg': 9, 'chance': 0.6},
        "desc": 'Проклятый прилив разъедает контур солёной ПЭ (60% кровотечение 2 хода).',
        "has_domain": False,
    },
    "Искажённая скульптура": {
        "emoji": '🗿', "name": 'Искажённая скульптура',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 34,
        "dmg_min": 24, "dmg_max": 32,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.55},
        "desc": 'Грубая перелепка тела противника на ходу (55% стан на 1 ход).',
        "has_domain": False,
    },
    "Клинок смертного полотна": {
        "emoji": '🗡️', "name": 'Клинок смертного полотна',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 33,
        "dmg_min": 23, "dmg_max": 30,
        "effect": {'type': 'bleed', 'turns': 3, 'dmg': 11, 'chance': 0.65},
        "desc": 'Клинок из загустевшей крови (65% кровотечение 3 хода).',
        "has_domain": False,
    },
    "Крушение созвездия": {
        "emoji": '🌠', "name": 'Крушение созвездия',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 34,
        "dmg_min": 25, "dmg_max": 33,
        "effect": None,
        "desc": 'Серия из семи ударов, каждый быстрее света.',
        "has_domain": False,
    },
    "Максимальный красный": {
        "emoji": '🟥', "name": 'Максимальный красный',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 36,
        "dmg_min": 30, "dmg_max": 40,
        "effect": {'type': 'bleed', 'turns': 2, 'dmg': 10, 'chance': 0.5},
        "desc": 'Красный, усиленный Обратной техникой до предела (50% кровотечение 2 хода).',
        "has_domain": False,
    },
    "Максимальный синий": {
        "emoji": '🔷', "name": 'Максимальный синий',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 36,
        "dmg_min": 26, "dmg_max": 34,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.5},
        "desc": 'Синий, доведённый до критической плотности (50% стан на 1 ход).',
        "has_domain": False,
    },
    "Пасть бездны": {
        "emoji": '🐺', "name": 'Пасть бездны',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 34,
        "dmg_min": 25, "dmg_max": 33,
        "effect": {'type': 'bleed', 'turns': 3, 'dmg': 13, 'chance': 0.7},
        "desc": 'Мастер-техника семьи Зверя из бездны (70% кровотечение 3 хода).',
        "has_domain": True,
    },
    "Пепельный прилив": {
        "emoji": '🌋', "name": 'Пепельный прилив',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 34,
        "dmg_min": 25, "dmg_max": 33,
        "effect": None,
        "desc": 'Волна тлеющего пепла накрывает область перед решающим выпадом.',
        "has_domain": False,
    },
    "Приговорный удар": {
        "emoji": '⚖️', "name": 'Приговорный удар',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 33,
        "dmg_min": 22, "dmg_max": 30,
        "effect": {'type': 'buff_dmg', 'turns': 1, 'mult': 1.6, 'chance': 1.0},
        "desc": 'Приговор, вынесенный без права на апелляцию (+60% урона на 1 ход).',
        "has_domain": False,
    },
    "Проклятая утроба: Натиск": {
        "emoji": '🩻', "name": 'Проклятая утроба: Натиск',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 33,
        "dmg_min": 23, "dmg_max": 31,
        "effect": None,
        "desc": 'Кэндзаку сшивает украденные техники в составной удар.',
        "has_domain": False,
    },
    "Рассечение": {
        "emoji": '⚔️', "name": 'Рассечение',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 38,
        "dmg_min": 30, "dmg_max": 40,
        "effect": {'type': 'bleed', 'turns': 3, 'dmg': 14, 'chance': 0.75},
        "desc": 'Усиленная версия Расщепления — лезвия ПЭ бьют с нескольких направлений (75% кровотечение 3 хода).',
        "has_domain": False,
    },
    "Скопированный клинок": {
        "emoji": '🗡️', "name": 'Скопированный клинок',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 34,
        "dmg_min": 24, "dmg_max": 32,
        "effect": None,
        "desc": 'Юта на лету копирует ближайшую технику противника и бьёт ей же.',
        "has_domain": False,
    },
    "Слово: Взорвись": {
        "emoji": '💢', "name": 'Слово: Взорвись',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 32,
        "dmg_min": 20, "dmg_max": 28,
        "effect": None,
        "desc": 'Самая опасная команда проклятой речи.',
        "has_domain": False,
    },
    "Смертельный удар перевёрнутым копьём": {
        "emoji": '🗡️', "name": 'Смертельный удар перевёрнутым копьём',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 30,
        "dmg_min": 22, "dmg_max": 30,
        "effect": None,
        "desc": 'Тоджи Фушигуро — чистая физика без магии.',
        "has_domain": False,
    },
    "Тысяча лун": {
        "emoji": '🌕', "name": 'Тысяча лун',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 37,
        "dmg_min": 27, "dmg_max": 36,
        "effect": {'type': 'bleed', 'turns': 3, 'dmg': 12, 'chance': 0.7},
        "desc": 'Мастер-техника семьи Лунного клинка (70% кровотечение 3 хода).',
        "has_domain": True,
    },
    "Шторм проклятой молнии": {
        "emoji": '🌩️', "name": 'Шторм проклятой молнии',
        "rarity": 'Мифическая', "category": '⚔️ Атака',
        "ce_cost": 35,
        "dmg_min": 26, "dmg_max": 34,
        "effect": {'type': 'stun', 'turns': 1, 'chance': 0.5},
        "desc": 'Мастер-техника семьи Грозы (50% стан на 1 ход).',
        "has_domain": True,
    },
    "Великий змей": {
        "emoji": '🐍', "name": 'Великий змей',
        "rarity": 'Мифическая', "category": '🛡 Защита',
        "ce_cost": 34,
        "dmg_min": 22, "dmg_max": 28,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.7, 'chance': 1.0},
        "desc": 'Шикигами-констриктор обвивает союзника (-30% получаемого урона на 2 хода).',
        "has_domain": False,
    },
    "Морозный плен": {
        "emoji": '🧊', "name": 'Морозный плен',
        "rarity": 'Мифическая', "category": '🛡 Защита',
        "ce_cost": 33,
        "dmg_min": 21, "dmg_max": 29,
        "effect": {'type': 'buff_def', 'turns': 2, 'mult': 0.65, 'chance': 1.0},
        "desc": 'Мастер-техника семьи Ледяного трона (-35% получаемого урона на 2 хода).',
        "has_domain": True,
    },
    "Несокрушимый кокон": {
        "emoji": '🔩', "name": 'Несокрушимый кокон',
        "rarity": 'Мифическая', "category": '🛡 Защита',
        "ce_cost": 33,
        "dmg_min": 20, "dmg_max": 27,
        "effect": {'type': 'buff_def', 'turns': 3, 'mult': 0.6, 'chance': 1.0},
        "desc": 'Мастер-техника семьи Стального кокона (-40% получаемого урона на 3 хода).',
        "has_domain": True,
    },
    "Договор крови": {
        "emoji": '🩸', "name": 'Договор крови',
        "rarity": 'Мифическая', "category": '🌀 Статус',
        "ce_cost": 34,
        "dmg_min": 20, "dmg_max": 28,
        "effect": {'type': 'buff_dmg', 'turns': 3, 'mult': 1.7, 'chance': 1.0},
        "desc": 'Мастер-техника семьи Кровавого пакта (+70% урона на 3 хода).',
        "has_domain": True,
    },
    "Крик пустоты": {
        "emoji": '📢', "name": 'Крик пустоты',
        "rarity": 'Мифическая', "category": '🌀 Статус',
        "ce_cost": 33,
        "dmg_min": 18, "dmg_max": 26,
        "effect": {'type': 'stun', 'turns': 2, 'chance': 0.6},
        "desc": 'Мастер-техника семьи Пустотного шёпота (60% стан на 2 хода).',
        "has_domain": True,
    },
    "Реквием скорби": {
        "emoji": '🎼', "name": 'Реквием скорби',
        "rarity": 'Мифическая', "category": '🌀 Статус',
        "ce_cost": 32,
        "dmg_min": 0, "dmg_max": 0,
        "effect": {'type': 'heal', 'turns': 0, 'amount': 30, 'chance': 1.0},
        "desc": 'Мастер-техника семьи Скорбной песни (мгновенно 30 HP).',
        "has_domain": True,
    },
    "Божественное рассечение мира": {
        "emoji": '🌀', "name": 'Божественное рассечение мира',
        "rarity": 'Легендарная (Особый класс)', "category": '⚔️ Атака',
        "ce_cost": 52,
        "dmg_min": 44, "dmg_max": 58,
        "effect": {'type': 'bleed', 'turns': 4, 'dmg': 18, 'chance': 0.85},
        "desc": 'Высшая форма техники Рассечения (85% кровотечение 4 хода).',
        "has_domain": True,
    },
    "Воплощение совершенства": {
        "emoji": '😈', "name": 'Воплощение совершенства',
        "rarity": 'Легендарная (Особый класс)', "category": '⚔️ Атака',
        "ce_cost": 54,
        "dmg_min": 40, "dmg_max": 52,
        "effect": {'type': 'bleed', 'turns': 3, 'dmg': 15, 'chance': 0.7},
        "desc": 'Финальная форма Махито (70% кровотечение 3 хода).',
        "has_domain": True,
    },
    "Горизонт пленительной скандхи": {
        "emoji": '🌊', "name": 'Горизонт пленительной скандхи',
        "rarity": 'Легендарная (Особый класс)', "category": '⚔️ Атака',
        "ce_cost": 52,
        "dmg_min": 38, "dmg_max": 50,
        "effect": {'type': 'stun', 'turns': 2, 'chance': 0.65},
        "desc": 'Мастер-техника Дагона (65% стан на 2 хода).',
        "has_domain": True,
    },
    "Пламя вулкана": {
        "emoji": '🌋', "name": 'Пламя вулкана',
        "rarity": 'Легендарная (Особый класс)', "category": '⚔️ Атака',
        "ce_cost": 53,
        "dmg_min": 42, "dmg_max": 56,
        "effect": {'type': 'bleed', 'turns': 3, 'dmg': 16, 'chance': 0.7},
        "desc": 'Метеоритный шторм Джого (70% кровотечение 3 хода).',
        "has_domain": True,
    },
    "Пустотный пурпур": {
        "emoji": '🟣', "name": 'Пустотный пурпур',
        "rarity": 'Легендарная (Особый класс)', "category": '⚔️ Атака',
        "ce_cost": 50,
        "dmg_min": 40, "dmg_max": 55,
        "effect": {'type': 'stun', 'turns': 2, 'chance': 0.7},
        "desc": 'Слияние Синего и Красного — мастер-техника семьи Бесконечности (70% стан на 2 хода).',
        "has_domain": True,
    },
    "Феникс из пепла": {
        "emoji": '🔥', "name": 'Феникс из пепла',
        "rarity": 'Легендарная (Особый класс)', "category": '⚔️ Атака',
        "ce_cost": 51,
        "dmg_min": 40, "dmg_max": 52,
        "effect": {'type': 'bleed', 'turns': 3, 'dmg': 15, 'chance': 0.7},
        "desc": 'Мастер-техника семьи Пепла (70% кровотечение 3 хода).',
        "has_domain": True,
    },
    "Бесконечный лабиринт отражений": {
        "emoji": '🪞', "name": 'Бесконечный лабиринт отражений',
        "rarity": 'Легендарная (Особый класс)', "category": '🛡 Защита',
        "ce_cost": 49,
        "dmg_min": 30, "dmg_max": 40,
        "effect": {'type': 'buff_def', 'turns': 3, 'mult': 0.55, 'chance': 1.0},
        "desc": 'Мастер-техника семьи Зеркал (-45% получаемого урона на 3 хода).',
        "has_domain": True,
    },
    "Призыв Махораги": {
        "emoji": '🌀', "name": 'Призыв Махораги',
        "rarity": 'Легендарная (Особый класс)', "category": '🛡 Защита',
        "ce_cost": 55,
        "dmg_min": 34, "dmg_max": 46,
        "effect": {'type': 'buff_def', 'turns': 3, 'mult': 0.5, 'chance': 1.0},
        "desc": 'Шикигами, адаптирующееся к любой технике противника (-50% получаемого урона на 3 хода).',
        "has_domain": True,
    },
    "Игра в Смерть на Досуге": {
        "emoji": '🎰', "name": 'Игра в Смерть на Досуге',
        "rarity": 'Легендарная (Особый класс)', "category": '🌀 Статус',
        "ce_cost": 50,
        "dmg_min": 20, "dmg_max": 60,
        "effect": {'type': 'buff_dmg', 'turns': 3, 'mult': 2.0, 'chance': 1.0},
        "desc": 'Мастер-техника Хакари — финальная ставка всей ПЭ (урон 20-60).',
        "has_domain": True,
    },
    "Истинная взаимная любовь": {
        "emoji": '💞', "name": 'Истинная взаимная любовь',
        "rarity": 'Легендарная (Особый класс)', "category": '🌀 Статус',
        "ce_cost": 53,
        "dmg_min": 30, "dmg_max": 45,
        "effect": {'type': 'buff_dmg', 'turns': 3, 'mult': 1.8, 'chance': 1.0},
        "desc": 'Мастер-техника Юты Оккоцу (+80% урона на 3 хода).',
        "has_domain": True,
    },
    "Отклонение утробы": {
        "emoji": '🔀', "name": 'Отклонение утробы',
        "rarity": 'Легендарная (Особый класс)', "category": '🌀 Статус',
        "ce_cost": 48,
        "dmg_min": 25, "dmg_max": 35,
        "effect": {'type': 'weaken', 'turns': 2, 'mult': 0.7, 'chance': 0.75},
        "desc": 'Высшая форма манипуляции плотью Кэндзаку (75% -30% урона цели на 2 хода).',
        "has_domain": False,
    },
    "Смертный приговор": {
        "emoji": '🔨', "name": 'Смертный приговор',
        "rarity": 'Легендарная (Особый класс)', "category": '🌀 Статус',
        "ce_cost": 51,
        "dmg_min": 30, "dmg_max": 40,
        "effect": {'type': 'stun', 'turns': 2, 'chance': 0.6},
        "desc": 'Высшая форма Домена Суда, применённая напрямую (60% стан на 2 хода).',
        "has_domain": True,
    },
}